import { Language, MovieStatus, PrismaClient } from '@prisma/client'

export async function seedMovies(prisma: PrismaClient) {
  const user = await prisma.user.upsert({
    where: { email: 'testuser@example.com' },
    update: {},
    create: {
      name: 'Usuário de Teste',
      email: 'testuser@example.com',
      password: 'hashed-password-placeholder',
    },
  })

  const genreNames = [
    'Ação',
    'Drama',
    'Comédia',
    'Ficção Científica',
    'Aventura',
    'Crime',
    'Suspense',
    'Animação',
    'Romance',
    'Terror',
    'Fantasia',
    'Musical',
    'Guerra',
    'Western',
    'Biografia',
  ]
  const genres: { id: string; name: string }[] = []

  for (const name of genreNames) {
    const genre = await prisma.genre.upsert({
      where: { name },
      update: {},
      create: { name },
    })
    genres.push(genre)
  }

  const movieData = [
    {
      title: 'Interestelar',
      slug: 'interestelar',
      originalTitle: 'Interstellar',
      description:
        'Em um futuro onde a Terra está se tornando inabitável, um grupo de astronautas viaja através de um buraco de minhoca em busca de um novo lar para a humanidade.',
      releaseDate: new Date('2014-11-07'),
      duration: 169,
      status: MovieStatus.RELEASED,
      language: Language.PT,
      userId: user.id,
      budget: 165000000,
      revenue: 701729206,
      popularity: 8.9,
      votes: 1500000,
      ratingPercentage: 88,
      genresToConnect: [
        genres.find((g) => g.name === 'Ficção Científica')!.id,
        genres.find((g) => g.name === 'Drama')!.id,
      ],
      tagline: 'A humanidade nasceu na Terra. Não morrerá aqui.',
    },
    {
      title: 'A Origem',
      slug: 'a-origem',
      originalTitle: 'Inception',
      description:
        'Um ladrão especializado em extrair segredos do subconsciente durante o estado de sono é oferecido uma chance de ter sua vida antiga de volta como pagamento para uma tarefa considerada impossível: "inserção".',
      releaseDate: new Date('2010-07-16'),
      duration: 148,
      status: MovieStatus.RELEASED,
      language: Language.PT,
      userId: user.id,
      budget: 160000000,
      revenue: 836836967,
      popularity: 8.8,
      votes: 2000000,
      ratingPercentage: 91,
      genresToConnect: [
        genres.find((g) => g.name === 'Ficção Científica')!.id,
        genres.find((g) => g.name === 'Ação')!.id,
      ],
      tagline: 'O sonho é real',
    },
    {
      title: 'Pulp Fiction: Tempo de Violência',
      slug: 'pulp-fiction',
      originalTitle: 'Pulp Fiction',
      description:
        'Vários eventos se entrelaçam em uma história não linear que envolve dois assassinos profissionais, um boxeador, um gângster e sua esposa, e um par de bandidos de restaurante.',
      releaseDate: new Date('1994-10-14'),
      duration: 154,
      status: MovieStatus.RELEASED,
      language: Language.PT,
      userId: user.id,
      budget: 8000000,
      revenue: 213928762,
      popularity: 8.7,
      votes: 1800000,
      ratingPercentage: 94,
      genresToConnect: [
        genres.find((g) => g.name === 'Crime')!.id,
        genres.find((g) => g.name === 'Drama')!.id,
      ],
      tagline: 'Você nunca viu nada igual',
    },
    {
      title: 'Toy Story',
      slug: 'toy-story',
      originalTitle: 'Toy Story',
      description:
        'Um cowboy de brinquedo se sente ameaçado e ciumento quando um novo brinquedo espacial se torna o favorito do menino que o possui.',
      releaseDate: new Date('1995-11-22'),
      duration: 81,
      status: MovieStatus.RELEASED,
      language: Language.PT,
      userId: user.id,
      budget: 30000000,
      revenue: 373554033,
      popularity: 8.3,
      votes: 1400000,
      ratingPercentage: 92,
      genresToConnect: [
        genres.find((g) => g.name === 'Animação')!.id,
        genres.find((g) => g.name === 'Aventura')!.id,
      ],
      tagline: 'O primeiro longa totalmente animado por computador do mundo',
    },
    {
      title: 'Cidade de Deus',
      slug: 'cidade-de-deus',
      originalTitle: 'Cidade de Deus',
      description:
        'Buscapé é um jovem pobre, negro e sensível, que cresce em um universo de muita violência. Ele vive na Cidade de Deus, favela carioca conhecida por ser um dos locais mais violentos do Rio.',
      releaseDate: new Date('2002-08-30'),
      duration: 130,
      status: MovieStatus.RELEASED,
      language: Language.PT,
      userId: user.id,
      budget: 3300000,
      revenue: 30600000,
      popularity: 8.6,
      votes: 700000,
      ratingPercentage: 91,
      genresToConnect: [
        genres.find((g) => g.name === 'Crime')!.id,
        genres.find((g) => g.name === 'Drama')!.id,
      ],
      tagline: 'Se correr o bicho pega, se ficar o bicho come',
    },
    {
      title: 'O Poderoso Chefão',
      slug: 'o-poderoso-chefao',
      originalTitle: 'The Godfather',
      description:
        'O patriarca de uma dinastia do crime organizado transfere o controle de seu império clandestino para seu filho relutante.',
      releaseDate: new Date('1972-03-24'),
      duration: 175,
      status: MovieStatus.RELEASED,
      language: Language.EN,
      userId: user.id,
      budget: 6000000,
      revenue: 287000000,
      popularity: 9.2,
      votes: 1700000,
      ratingPercentage: 97,
      genresToConnect: [
        genres.find((g) => g.name === 'Crime')!.id,
        genres.find((g) => g.name === 'Drama')!.id,
      ],
      tagline: 'Uma oferta que você não pode recusar',
    },
    {
      title: 'Forrest Gump',
      slug: 'forrest-gump',
      originalTitle: 'Forrest Gump',
      description:
        'As presidências de Kennedy e Johnson, a Guerra do Vietnã, o escândalo Watergate e outros eventos históricos se desenrolam através da perspectiva de um homem do Alabama com QI de 75.',
      releaseDate: new Date('1994-07-06'),
      duration: 142,
      status: MovieStatus.RELEASED,
      language: Language.EN,
      userId: user.id,
      budget: 55000000,
      revenue: 678200000,
      popularity: 8.8,
      votes: 1900000,
      ratingPercentage: 89,
      genresToConnect: [
        genres.find((g) => g.name === 'Drama')!.id,
        genres.find((g) => g.name === 'Romance')!.id,
      ],
      tagline: 'A vida é como uma caixa de chocolates',
    },
    {
      title: 'Matrix',
      slug: 'matrix',
      originalTitle: 'The Matrix',
      description:
        'Um hacker descobre que a realidade como ele a conhece é uma simulação e se junta a uma rebelião contra as máquinas que controlam a humanidade.',
      releaseDate: new Date('1999-03-31'),
      duration: 136,
      status: MovieStatus.RELEASED,
      language: Language.EN,
      userId: user.id,
      budget: 63000000,
      revenue: 467200000,
      popularity: 8.7,
      votes: 1600000,
      ratingPercentage: 88,
      genresToConnect: [
        genres.find((g) => g.name === 'Ficção Científica')!.id,
        genres.find((g) => g.name === 'Ação')!.id,
      ],
      tagline: 'A realidade é uma ilusão',
    },
    {
      title: 'Titanic',
      slug: 'titanic',
      originalTitle: 'Titanic',
      description:
        'Um aristocrata de dezessete anos se apaixona por um artista gentil, mas pobre, a bordo do luxuoso e mal-fadado R.M.S. Titanic.',
      releaseDate: new Date('1997-12-19'),
      duration: 194,
      status: MovieStatus.RELEASED,
      language: Language.EN,
      userId: user.id,
      budget: 200000000,
      revenue: 2200000000,
      popularity: 7.9,
      votes: 1100000,
      ratingPercentage: 84,
      genresToConnect: [
        genres.find((g) => g.name === 'Romance')!.id,
        genres.find((g) => g.name === 'Drama')!.id,
      ],
      tagline: 'Nada na Terra poderia separá-los',
    },
    {
      title: 'O Senhor dos Anéis: A Sociedade do Anel',
      slug: 'senhor-dos-aneis-sociedade',
      originalTitle: 'The Lord of the Rings: The Fellowship of the Ring',
      description:
        'Um hobbit relutante, Bilbo Baggins, parte para a Montanha Solitária com um grupo vigoroso de anões para reclamar sua casa na montanha e o ouro dentro dela do dragão Smaug.',
      releaseDate: new Date('2001-12-19'),
      duration: 178,
      status: MovieStatus.RELEASED,
      language: Language.EN,
      userId: user.id,
      budget: 93000000,
      revenue: 897700000,
      popularity: 8.8,
      votes: 1700000,
      ratingPercentage: 91,
      genresToConnect: [
        genres.find((g) => g.name === 'Fantasia')!.id,
        genres.find((g) => g.name === 'Aventura')!.id,
      ],
      tagline: 'Uma jornada épica começa',
    },
    {
      title: 'Vingadores: Ultimato',
      slug: 'vingadores-ultimato',
      originalTitle: 'Avengers: Endgame',
      description:
        'Após os eventos devastadores de Vingadores: Guerra Infinita, o universo está em ruínas. Com a ajuda de aliados remanescentes, os Vingadores se reúnem mais uma vez.',
      releaseDate: new Date('2019-04-26'),
      duration: 181,
      status: MovieStatus.RELEASED,
      language: Language.EN,
      userId: user.id,
      budget: 356000000,
      revenue: 2797800000,
      popularity: 8.4,
      votes: 900000,
      ratingPercentage: 85,
      genresToConnect: [
        genres.find((g) => g.name === 'Ação')!.id,
        genres.find((g) => g.name === 'Aventura')!.id,
      ],
      tagline: 'Parte da jornada é o fim',
    },
    {
      title: 'Parasita',
      slug: 'parasita',
      originalTitle: 'Parasite',
      description:
        'Greed and class discrimination threaten the newly formed symbiotic relationship between the wealthy Park family and the destitute Kim clan.',
      releaseDate: new Date('2019-05-30'),
      duration: 132,
      status: MovieStatus.RELEASED,
      language: Language.EN,
      userId: user.id,
      budget: 11400000,
      revenue: 263500000,
      popularity: 8.5,
      votes: 700000,
      ratingPercentage: 96,
      genresToConnect: [
        genres.find((g) => g.name === 'Suspense')!.id,
        genres.find((g) => g.name === 'Drama')!.id,
      ],
      tagline: 'Você pode sentir o cheiro atravessando a linha',
    },
    {
      title: 'Coringa',
      slug: 'coringa',
      originalTitle: 'Joker',
      description:
        'Em Gotham City, Arthur Fleck, um comediante fracassado, é levado ao crime e ao caos na cidade de Gotham através de uma espiral descendente de revolução social e vingança pessoal.',
      releaseDate: new Date('2019-10-04'),
      duration: 122,
      status: MovieStatus.RELEASED,
      language: Language.EN,
      userId: user.id,
      budget: 55000000,
      revenue: 1074000000,
      popularity: 8.4,
      votes: 1200000,
      ratingPercentage: 81,
      genresToConnect: [
        genres.find((g) => g.name === 'Crime')!.id,
        genres.find((g) => g.name === 'Drama')!.id,
      ],
      tagline: 'Coloque um sorriso nesse rosto',
    },
    {
      title: 'Pantera Negra',
      slug: 'pantera-negra',
      originalTitle: 'Black Panther',
      description:
        "T'Challa, herdeiro do reino escondido e altamente avançado de Wakanda, deve dar um passo à frente para liderar seu povo em uma nova era.",
      releaseDate: new Date('2018-02-16'),
      duration: 134,
      status: MovieStatus.RELEASED,
      language: Language.EN,
      userId: user.id,
      budget: 200000000,
      revenue: 1347000000,
      popularity: 7.3,
      votes: 700000,
      ratingPercentage: 79,
      genresToConnect: [
        genres.find((g) => g.name === 'Ação')!.id,
        genres.find((g) => g.name === 'Aventura')!.id,
      ],
      tagline: 'Longa vida ao rei',
    },
    {
      title: 'La La Land',
      slug: 'la-la-land',
      originalTitle: 'La La Land',
      description:
        'Enquanto navegam por suas carreiras em Los Angeles, um pianista e uma atriz se apaixonam enquanto tentam conciliar suas aspirações para o futuro.',
      releaseDate: new Date('2016-12-09'),
      duration: 128,
      status: MovieStatus.RELEASED,
      language: Language.EN,
      userId: user.id,
      budget: 30000000,
      revenue: 448900000,
      popularity: 8.0,
      votes: 500000,
      ratingPercentage: 83,
      genresToConnect: [
        genres.find((g) => g.name === 'Musical')!.id,
        genres.find((g) => g.name === 'Romance')!.id,
      ],
      tagline: 'Aqui está para os sonhadores',
    },
    {
      title: 'Mad Max: Estrada da Fúria',
      slug: 'mad-max-estrada-furia',
      originalTitle: 'Mad Max: Fury Road',
      description:
        'Em um mundo pós-apocalíptico, Max Rockatansky se junta à Imperatriz Furiosa para fugir de um senhor da guerra que os persegue através do deserto.',
      releaseDate: new Date('2015-05-15'),
      duration: 120,
      status: MovieStatus.RELEASED,
      language: Language.EN,
      userId: user.id,
      budget: 150000000,
      revenue: 378900000,
      popularity: 8.1,
      votes: 900000,
      ratingPercentage: 90,
      genresToConnect: [
        genres.find((g) => g.name === 'Ação')!.id,
        genres.find((g) => g.name === 'Aventura')!.id,
      ],
      tagline: 'O que um homem louco pode fazer?',
    },
    {
      title: 'Coco',
      slug: 'coco',
      originalTitle: 'Coco',
      description:
        'Aspirante a músico Miguel, confrontado com a proibição de música de sua família, entra na Terra dos Mortos para encontrar seu tataravô, um lendário cantor.',
      releaseDate: new Date('2017-11-22'),
      duration: 105,
      status: MovieStatus.RELEASED,
      language: Language.ES,
      userId: user.id,
      budget: 175000000,
      revenue: 807800000,
      popularity: 8.4,
      votes: 400000,
      ratingPercentage: 90,
      genresToConnect: [
        genres.find((g) => g.name === 'Animação')!.id,
        genres.find((g) => g.name === 'Musical')!.id,
      ],
      tagline: 'A música é vida',
    },
    {
      title: 'O Resgate do Soldado Ryan',
      slug: 'resgate-soldado-ryan',
      originalTitle: 'Saving Private Ryan',
      description:
        'Após o desembarque na Normandia, um grupo de soldados americanos vai atrás de um paraquedista cujos irmãos foram mortos em ação.',
      releaseDate: new Date('1998-07-24'),
      duration: 169,
      status: MovieStatus.RELEASED,
      language: Language.EN,
      userId: user.id,
      budget: 70000000,
      revenue: 482300000,
      popularity: 8.6,
      votes: 1300000,
      ratingPercentage: 94,
      genresToConnect: [
        genres.find((g) => g.name === 'Guerra')!.id,
        genres.find((g) => g.name === 'Drama')!.id,
      ],
      tagline: 'A missão é um homem',
    },
    {
      title: 'O Iluminado',
      slug: 'o-iluminado',
      originalTitle: 'The Shining',
      description:
        'Uma família vai para um hotel isolado para o inverno onde uma presença sinistra influencia o pai à violência, enquanto seu filho psíquico vê horríveis premonições do passado e do futuro.',
      releaseDate: new Date('1980-05-23'),
      duration: 146,
      status: MovieStatus.RELEASED,
      language: Language.EN,
      userId: user.id,
      budget: 19000000,
      revenue: 47300000,
      popularity: 8.4,
      votes: 900000,
      ratingPercentage: 85,
      genresToConnect: [
        genres.find((g) => g.name === 'Terror')!.id,
        genres.find((g) => g.name === 'Suspense')!.id,
      ],
      tagline: 'Aqui está Johnny!',
    },
    {
      title: 'Clube da Luta',
      slug: 'clube-da-luta',
      originalTitle: 'Fight Club',
      description:
        'Um funcionário de escritório insone e um fabricante de sabão formam um clube de luta subterrâneo que evolui para algo muito, muito mais.',
      releaseDate: new Date('1999-10-15'),
      duration: 139,
      status: MovieStatus.RELEASED,
      language: Language.EN,
      userId: user.id,
      budget: 63000000,
      revenue: 101200000,
      popularity: 8.8,
      votes: 1900000,
      ratingPercentage: 79,
      genresToConnect: [
        genres.find((g) => g.name === 'Drama')!.id,
        genres.find((g) => g.name === 'Suspense')!.id,
      ],
      tagline:
        'A primeira regra do Clube da Luta é: você não fala sobre o Clube da Luta',
    },
    {
      title: 'Gladiador',
      slug: 'gladiador',
      originalTitle: 'Gladiator',
      description:
        'Um ex-general romano se propõe a vingar o assassinato de sua família pelo filho corrupto do imperador.',
      releaseDate: new Date('2000-05-05'),
      duration: 155,
      status: MovieStatus.RELEASED,
      language: Language.EN,
      userId: user.id,
      budget: 103000000,
      revenue: 460500000,
      popularity: 8.5,
      votes: 1400000,
      ratingPercentage: 76,
      genresToConnect: [
        genres.find((g) => g.name === 'Ação')!.id,
        genres.find((g) => g.name === 'Drama')!.id,
      ],
      tagline: 'Força e honra',
    },
    {
      title: 'Casablanca',
      slug: 'casablanca',
      originalTitle: 'Casablanca',
      description:
        'Um expatriado americano cínico encontra seu antigo amor no Marrocos controlado pelos nazistas e deve escolher entre o amor e a virtude.',
      releaseDate: new Date('1942-11-26'),
      duration: 102,
      status: MovieStatus.RELEASED,
      language: Language.EN,
      userId: user.id,
      budget: 1000000,
      revenue: 10600000,
      popularity: 8.5,
      votes: 500000,
      ratingPercentage: 97,
      genresToConnect: [
        genres.find((g) => g.name === 'Drama')!.id,
        genres.find((g) => g.name === 'Romance')!.id,
      ],
      tagline: 'Sempre teremos Paris',
    },
    {
      title: 'O Cavaleiro das Trevas',
      slug: 'cavaleiro-das-trevas',
      originalTitle: 'The Dark Knight',
      description:
        'Quando a ameaça conhecida como Coringa emerge de seu passado misterioso, ele causa estragos e caos no povo de Gotham.',
      releaseDate: new Date('2008-07-18'),
      duration: 152,
      status: MovieStatus.RELEASED,
      language: Language.EN,
      userId: user.id,
      budget: 185000000,
      revenue: 1005000000,
      popularity: 9.0,
      votes: 2500000,
      ratingPercentage: 94,
      genresToConnect: [
        genres.find((g) => g.name === 'Ação')!.id,
        genres.find((g) => g.name === 'Crime')!.id,
      ],
      tagline: 'Por que tão sério?',
    },
    {
      title: 'Shrek',
      slug: 'shrek',
      originalTitle: 'Shrek',
      description:
        'Um ogro recluso e um burro falante partem em uma missão para resgatar uma princesa para um lorde tirânico.',
      releaseDate: new Date('2001-05-18'),
      duration: 90,
      status: MovieStatus.RELEASED,
      language: Language.EN,
      userId: user.id,
      budget: 60000000,
      revenue: 484400000,
      popularity: 7.9,
      votes: 600000,
      ratingPercentage: 78,
      genresToConnect: [
        genres.find((g) => g.name === 'Animação')!.id,
        genres.find((g) => g.name === 'Comédia')!.id,
      ],
      tagline:
        'A história que você conhece. Os personagens que você não conhece.',
    },
    {
      title: 'Procurando Nemo',
      slug: 'procurando-nemo',
      originalTitle: 'Finding Nemo',
      description:
        'Depois que seu filho é capturado no Grande Recife de Coral e levado para Sydney, um peixe-palhaço tímido parte em uma jornada para trazê-lo para casa.',
      releaseDate: new Date('2003-05-30'),
      duration: 100,
      status: MovieStatus.RELEASED,
      language: Language.EN,
      userId: user.id,
      budget: 94000000,
      revenue: 940300000,
      popularity: 8.2,
      votes: 900000,
      ratingPercentage: 90,
      genresToConnect: [
        genres.find((g) => g.name === 'Animação')!.id,
        genres.find((g) => g.name === 'Aventura')!.id,
      ],
      tagline:
        'Há 3,7 trilhões de peixes no oceano... eles estão procurando por um.',
    },
    {
      title: 'Duna',
      slug: 'duna',
      originalTitle: 'Dune',
      description:
        'Paul Atreides, um jovem brilhante e talentoso nascido em um grande destino além de sua compreensão, deve viajar para o planeta mais perigoso do universo.',
      releaseDate: new Date('2021-10-22'),
      duration: 155,
      status: MovieStatus.RELEASED,
      language: Language.EN,
      userId: user.id,
      budget: 165000000,
      revenue: 401800000,
      popularity: 8.0,
      votes: 600000,
      ratingPercentage: 83,
      genresToConnect: [
        genres.find((g) => g.name === 'Ficção Científica')!.id,
        genres.find((g) => g.name === 'Aventura')!.id,
      ],
      tagline: 'Sonhos são mensagens do profundo',
    },
    {
      title: 'Top Gun: Maverick',
      slug: 'top-gun-maverick',
      originalTitle: 'Top Gun: Maverick',
      description:
        'Depois de mais de trinta anos de serviço como um dos principais aviadores da Marinha, Pete "Maverick" Mitchell está onde pertence.',
      releaseDate: new Date('2022-05-27'),
      duration: 130,
      status: MovieStatus.RELEASED,
      language: Language.EN,
      userId: user.id,
      budget: 170000000,
      revenue: 1488700000,
      popularity: 8.3,
      votes: 400000,
      ratingPercentage: 86,
      genresToConnect: [
        genres.find((g) => g.name === 'Ação')!.id,
        genres.find((g) => g.name === 'Drama')!.id,
      ],
      tagline: 'Sinta a necessidade... a necessidade de velocidade',
    },
    {
      title: 'Avatar: O Caminho da Água',
      slug: 'avatar-caminho-agua',
      originalTitle: 'Avatar: The Way of Water',
      description:
        'Jake Sully vive com sua nova família formada no planeta Pandora. Quando uma ameaça familiar retorna para terminar o que foi iniciado anteriormente.',
      releaseDate: new Date('2022-12-16'),
      duration: 192,
      status: MovieStatus.RELEASED,
      language: Language.EN,
      userId: user.id,
      budget: 350000000,
      revenue: 2320000000,
      popularity: 7.6,
      votes: 300000,
      ratingPercentage: 76,
      genresToConnect: [
        genres.find((g) => g.name === 'Ficção Científica')!.id,
        genres.find((g) => g.name === 'Aventura')!.id,
      ],
      tagline: 'Retorne ao mundo de Pandora',
    },
    {
      title: 'Homem-Aranha: Sem Volta Para Casa',
      slug: 'homem-aranha-sem-volta-casa',
      originalTitle: 'Spider-Man: No Way Home',
      description:
        'Com a identidade do Homem-Aranha revelada, Peter pede ajuda ao Doutor Estranho. Quando um feitiço dá errado, inimigos perigosos de outros mundos começam a aparecer.',
      releaseDate: new Date('2021-12-17'),
      duration: 148,
      status: MovieStatus.RELEASED,
      language: Language.EN,
      userId: user.id,
      budget: 200000000,
      revenue: 1921800000,
      popularity: 8.2,
      votes: 600000,
      ratingPercentage: 90,
      genresToConnect: [
        genres.find((g) => g.name === 'Ação')!.id,
        genres.find((g) => g.name === 'Aventura')!.id,
      ],
      tagline: 'O multiverso está quebrado',
    },
  ]

  for (const movie of movieData) {
    const existing = await prisma.movie.findUnique({
      where: { slug: movie.slug },
    })
    if (!existing) {
      await prisma.movie.create({
        data: {
          title: movie.title,
          slug: movie.slug,
          originalTitle: movie.originalTitle,
          description: movie.description,
          releaseDate: movie.releaseDate,
          duration: movie.duration,
          status: movie.status,
          language: movie.language,
          userId: movie.userId,
          budget: movie.budget,
          revenue: movie.revenue,
          popularity: movie.popularity,
          votes: movie.votes,
          ratingPercentage: movie.ratingPercentage,
          tagline: movie.tagline,
          genres: {
            connect: movie.genresToConnect.map((id) => ({ id })),
          },
        },
      })
    }
  }
}
